// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dta.Marketplace.Subscribers.Email.Logger.Worker.Model;
//
//    var vcapServices = VcapServices.FromJson(jsonString);

using System;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Dta.Marketplace.Subscribers.Email.Logger.Worker.Model {

    public partial class Attributes
    {
        [JsonProperty("ApproximateFirstReceiveTimestamp")]
        public string ApproximateFirstReceiveTimestamp { get; set; }

        [JsonProperty("SenderId")]
        public string SenderId { get; set; }

        [JsonProperty("ApproximateReceiveCount")]
        public long ApproximateReceiveCount { get; set; }

        [JsonProperty("SentTimestamp")]
        public string SentTimestamp { get; set; }
    }
    public partial class AwsSqsMessage
    {
        [JsonProperty("Body")]
        public string Body { get; set; }

        [JsonProperty("Attributes")]
        public Attributes Attributes { get; set; }

        [JsonProperty("ReceiptHandle")]
        public string ReceiptHandle { get; set; }

        [JsonProperty("MD5OfBody")]
        public string Md5OfBody { get; set; }

        [JsonProperty("MessageId")]
        public string MessageId { get; set; }
    }

        public partial class AwsSqsMessage {
        public static AwsSqsMessage FromJson(string json) => JsonConvert.DeserializeObject<AwsSqsMessage>(json, Converter.Settings);
    }
}