// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dta.Marketplace.Subscriber.Slack.Model;
//
//    var vcapServices = VcapServices.FromJson(jsonString);

using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Dta.Marketplace.Subscriber.Slack.Model {

    public partial class AwsSnsMessage {
        [JsonProperty("Message")]
        public string Message { get; set; }

        [JsonProperty("MessageAttributes")]
        public MessageAttributes MessageAttributes { get; set; }
    }

    public partial class MessageAttributes {
        [JsonProperty("object_type")]
        public TType ObjectType { get; set; }

        [JsonProperty("event_type")]
        public TType EventType { get; set; }
    }

    public partial class TType {
        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Value")]
        public string Value { get; set; }
    }

    public partial class AwsSnsMessage {
        public static AwsSnsMessage FromJson(string json) => JsonConvert.DeserializeObject<AwsSnsMessage>(json, Converter.Settings);
    }
}
