// <auto-generated />
using System;
using Dta.Marketplace.Subscribers.Email.Logger.Worker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace worker.Migrations
{
    [DbContext(typeof(EmailLoggerContext))]
    partial class EmailLoggerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dta.Marketplace.Subscribers.Email.Logger.Worker.EmailLogging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateTimeSent")
                        .HasColumnName("date_time_sent");

                    b.Property<string>("Message_Id")
                        .HasColumnName("message_id");

                    b.Property<string>("Notification_Type")
                        .HasColumnName("notification_type");

                    b.Property<string>("Subject")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("email_logging");
                });
#pragma warning restore 612, 618
        }
    }
}
